---
engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/*.js
exclude_paths:
- src/js/*.js
- jsamine/build/
- gulpfile.js