---
engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  duplication:
    enabled: true
    checks:
      no-unused-vars:
        enabled: false
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/*.js
exclude_paths:
- jasmine/build/
- jasmine/lib/
- gulpfile.js

