engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
  config:
    languages:
    - javascript
  checks:
    import/no-unresolved:
      enabled: false
     Similar code:
      enabled: false
ratings:
  paths:
  - src/*.js
exclude_paths: []