engines:
  eslint:
    enabled: true
fixme:
  enabled: true
channel: "eslint-2"
checks:
  Similar code:
    enabled: false
config:
  languages:
  - javascript
ratings:
  paths:
  - src
/*.js
exclude_paths:
- src/js/*.js
- jasmine/build/
- jasmine/lib/
- gulpfile.js
