engines:
 eslint:
   enabled: true
   channel: "eslint-2"
 duplication:
   enabled: true
   checks:
    import/no-unresolved:
      enabled: false
     Similar code:
      enabled: false
   config:
     languages:
     - javascript
ratings:
 paths:
 - src/*.js
exclude_paths: []
