engines:
  eslint:
    enabled: true
fixme:
  enabled: true
channel: "eslint-3"
checks:
  Similar code:
    enabled: false
  import/no-unresolved:
    enabled: false
config:
  languages:
  - javascript
ratings:
  paths:
  - src/*.js
exclude_paths:
- jasmine/build/
- jasmine/lib/
- gulpfile.js
