dist: trusty
language: node_js
node_js:
  - node
script: npm test
after_script:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
addons:
    code_climate:
        repo_token: 15bf83a2bac03fdb743f3feced294da29af15976c834023239f7e1b6bed8d03d